version: '3'

services:
  emqx1:
    image: emqx/emqx:5.2.1
    container_name: emqx
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 
    volumes:
      - ./emqx1_data:/opt/emqx/data